apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/grafana-etc
    server: 127.0.0.1
    readOnly: false
