apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-lib
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/grafana-lib
    server: 127.0.0.1
    readOnly: false
